### PR TITLE
Refactor code and add arguments

### PR DESCRIPTION
**Pull request by desilinguist**
Thanks for the really useful script! I made it possible to specify the various parameters directly on the command line and made the code a bit more readable. I also added `requirements.txt` and `environment.yaml` files to make it easy to install the dependencies.

### CODE REVIEW

**Comment by nhenderson** [comment]
@desilinguist line 46 throws this error when run with the `--total` option:
```
Traceback (most recent call last):
  File "/vaccine.py", line 85, in <module>
    main()
  File "/vaccine.py", line 47, in main
    max_time = time.time() + args.total_hours * 60 * 60
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```
To fix this issue, cast the `string` as an `int` like so:
```

**Comment by desilinguist** [comment]
Thanks @nhenderson! It's simpler to just make `total` an int in its argparse declaration. It should work now.

**Comment by nhenderson** [comment]
Ah yes, `type=int,` in `add.argument` will work too :-) Thanks for fixing that!

**Comment by burgamacha** [comment]
LGTM! Thanks for your contribution. Will add some props to you on the medium article for the PR!

**Pull request merged**
