### PR TITLE
Geolocation & command-line args

### PR DESCRIPTION
**Pull request by massenz**
Again, just contributing back as a courtesy - this is a bit of a deeper surgery :laughing: 
It also requires a Google API Key, which may or may not something you want to add to your code.

Feel free to close this PR without merging, no hard feelings!

(this needs to be merged **after** PR #4 , or it will cause conflicts)

### CODE REVIEW

**Comment by burgamacha** [comment]
Yikes! Would love to test and re-integrate this, but it's closed

**Comment by massenz** [comment]
Apologies, but I realized that this uses GPL:

>Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license.

this would have meant that if I ever decided to use any of **my own** code in future, anywhere else, I would have to release that "larger work" under the GPL too (and even assuming I wanted to open source it, it would have meant that anyone using it would have the same reservation).

I really encourage you to use the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0) instead, as it's more lenient and easier to use, adopt and integrate.

**Comment by burgamacha** [comment]
What a n00b mistake - I didn't even check to see what license it was released as. Thank you, and apologies. You can see the license.MD file is updated, and the repo has the correct license.

**Comment by massenz** [comment]
haha not a n00b at all! You must spend hours around corporate lawyers to the point you want to carve your own eyes out with a rusty spoon before you start to care about this stuff :laughing: 

Unfortunately, soon as I realized *my* mistake, I dismantled all the existing code (it was "tainted" by the GNU license) and rebuilt it very differently - essentially all that's left is the URL to CVS (which arguably was already "in the public domain" prior to the creation of the GNU-licensed code): so a PR now would be equivalent to deleting your repo and replacing it with mine.

Let me figure out if I can share the Googlemaps code, as that one is interesting and could probably be easily integrated into your code if you want.

May take a bit, though, as I'm currently busy at work; however, you can probably see it in the PR, by all means feel free to reuse it, I don't mind at all.

Thanks for changing the license, much appreciated!

**Pull request closed without merging**
